### ISSUE TITLE
Add support for defining route handler as a function reference

### ISSUE THREAD

**Issue by Wnt** [akheron/typera-openapi#123]
I would like to define my route handlers in an external file and use them in my routes.ts like:
```
import {registerHandler} from "./controllers/register";

const subscriptionRoute = route
  .post('/register')
  .use(Parser.body(registerSubscriptionBody))
  .handler(registerHandler)
```

but typera-openapi does not understand that route expression and gives a warning:
`warn: Handler is not a function`

**Comment by akheron** [comment]
Fix released in v0.11.2
