### ISSUE TITLE
Type aliases do not seem to work in route handlers

### ISSUE THREAD

**Issue by akolu** [akheron/typera-openapi#130]
For some reason type aliases in route handlers do not seem to be working when running `npx typera-openapi`, for example the following does not generate the openapi documentation for a route correctly:
```
type GetTextHandler = Route<Response.Ok<string> | Response.BadRequest<{ error: string }>>
const handler: GetTextHandler = route.get('/').handler( ... )
```

**Comment by akheron** [comment]
Fix released in v0.11.3
