### ISSUE TITLE
allow importing routes from other files

### ISSUE THREAD

**Issue by juliuste** [akheron/typera-openapi#152]
First of all, thank you so much for developing this cool library. This is exactly what I always thought was missing for a good developer experience regarding OpenAPI documentation with express and typescript.

## Problem

Currently, importing routes from other files is not supported. When having a file `index.ts` with the following content:

```ts
import { router } from 'typera-express'
import myRouteA from './my-route-a';
import { myRouteB, myRouteC } from './my-other-routes';

export default router(myRouteA, myRouteB, myRouteC);
```

calling `typera-openapi index.ts` will ignore the routes' parameters and instead output to `index.openapi.ts`:

```ts
import { OpenAPIV3 } from 'openapi-types'

const spec: { paths: OpenAPIV3.PathsObject } = {"paths":{}};

export default spec;
```

## Expected behaviour

I would either expect to get an error when running the CLI in this case (less preferable), or for the tool to correctly resolve the imports. I'm not sure how easy this is with the current setup of how the typescript compiler APIs get called. Maybe using an abstraction/helper for the TS compiler API like [ts-morph](https://www.npmjs.com/package/ts-morph) could be useful.

**Comment by akheron** [comment]
Fix released in v1.0.1
