### ISSUE TITLE
support JSDoc comments for query parameters

### ISSUE THREAD

**Issue by juliuste** [akheron/typera-openapi#160]
Sorry for opening another issue 😅. It would be really cool if the mechanism of translating the JSDoc comments in interfaces and io-ts codecs to descriptions in the openapi document would also work for query parameters, when using typera's `Parser.query(SomeSchema)`, the same way it is already working for `Parser.body(SomeSchema)`.

**Comment by akheron** [comment]
No problem! Fixed in v1.0.2.
