### ISSUE TITLE
add a way to expose example values for parameters

### ISSUE THREAD

**Issue by juliuste** [akheron/typera-openapi#165]
> *Disclaimer: Sorry for opening yet another issue, please close if out of scope/not useful. I'm currently integrating this library into a project that previously had a hand-written openapi doc, so I'm creating an issue here everytime I encounter a situation where the library doesn't (yet) allow what can be achieved by hand.*

Most objects in an OpenAPI document can have an `example` property, it would be really cool if this library provided a way to also optionally supply custom example values for parameters/body properties, e.g. with the `@example` JSDoc tag.

**Comment by akheron** [comment]
Thanks for opening the issues! Real use cases are the best way to add meaningful features.

I’ve been a bit busy lately, but will return to your suggestions. Just wanted to acknowledge that I’ve seen them 🙂
