### ISSUE TITLE
support documentation for path parameters

### ISSUE THREAD

**Issue by juliuste** [akheron/typera-openapi#167]
> *Disclaimer: Sorry for opening yet another issue, please close if out of scope/not useful. I'm currently integrating this library into a project that previously had a hand-written openapi doc, so I'm creating an issue here everytime I encounter a situation where the library doesn't (yet) allow what can be achieved by hand.*

It would be cool if the library provided a way to add docs for path parameters. I'm not sure where exactly one would put the corresponding JSDoc comments, maybe in the `Route`s main comment block, as is already the case for annotations to `@response` codes.

**Comment by akheron** [comment]
Fixed in #677
