### ISSUE TITLE
Should exit with an error if a source file contains no routes

### ISSUE THREAD

**Issue by Giesch** [akheron/typera-openapi#301]
In my app, I was generating routes from a function call, like this:

```ts
export default appRouter(deps);
```

Where 'deps' was some injected dependencies, like:
```ts
interface AppDependencies {
  db: Pool;
  config: Config;
}
```

This resulted in typera-openapi failing to generate, without any error message. Rearranging things to make the route information directly available resulted in everything working fine. I'd imagine that handling the general case for this would be overly complex. But it would be useful to have an error message.

**Comment by akheron** [comment]
> I'd imagine that handling the general case for this would be overly complex.

Exactly. This would be quite hard with the TypeScript compiler API.

> But it would be useful to have an error message.

Fixed in #346
