### ISSUE TITLE
Add support for spread router arguments

### ISSUE THREAD

**Issue by Wnt** [akheron/typera-openapi#349]
I would like to define my routes in separate files like:
```
const addItem = route.put('/item/:itemId').handler(() => Response.notImplemented())
const deleteItem = route.delete('/item/:itemId').handler(() => Response.notImplemented())

export const itemRoutes = [addItem, deleteItem]
```
and then in my main router file (`src/routes/index.ts`) do
```
import { router } from 'typera-express'
import { itemRoutes } from './item'

export default router(
  ...itemRoutes
)
```
but currently if I run `typera-openapi src/routes/index.ts` it fails to generate openapi. Typera itself works fine for those spread routes.

Please add support for reading spread router arguments in typera-openapi.

**Comment by akheron** [comment]
I tried to implement this, but seems that it's quite hard with the TypeScript compiler API.

In any case, it would probably be a better idea to make routers composable, so that you could add routers to other routers.

**Comment by tsheaff** [comment]
@akheron my understanding is that we can *only* use the `typera-openapi` command line for files that

```ts
export default router(myRoute);
```

and that no other syntax works, meaning we must define one route per file?

I tried all of the following alternatives.

```ts
export const myRouteA = router(myRouteA);
export const myRouteB = router(myRouteB);
```

```ts
export default [ router(myRouteA), router(myRouteB) ];
```

```ts
export default { myRouteA: router(myRouteA), myRouteB: router(myRouteB) };
```

I define multiple routes in a single file (e.g. the `user.ts` handler file defines ~10 routes all related to user fetch, user auth, user update etc.) changing this to one file per route to get the docs working is quite a pain.

**Comment by akheron** [comment]
`router()` accepts an arbitrary number of parameters. Just pass all your routes to it: `export default router(myRouteA, myRouteB)`
