### ISSUE TITLE
Route operationId support

### ISSUE THREAD

**Issue by amirilovic** [akheron/typera-openapi#528]
Hi, thanks for this wonderful library! I really enjoy using it.

I've been experimenting with generating typescript client using https://github.com/ferdikoomen/openapi-typescript-codegen. I noticed that generator uses operationId on a route to create nice function names, for example:

if I have route like:
```
 "/api/me": {
      "get": {
        "tags": ["me"],
...
}
```

generator by default creates something like:

```
apiClient.me.getApiMe()
```
If I add operationId like:
```
"/api/me": {
      "get": {
        "operationId": "getMeInfo",
        "tags": ["me"],
...
}
```

Generator creates:
```
apiClient.me.getMeInfo()
```

As far as I saw there is no way to do this currently with typera-openapi.

Would it make sense to add it? What are your thoughts how to do it? I could try to do quick PR for that.

Cheers!

**Comment by akheron** [comment]
Sounds very useful to me!

The first thing that comes to mind is using the route's name as the operation id, and make it possible to override in the JSDoc comment somehow:

From README:
```
const myRoute: Route<Response.Ok<MyResult> | Response.BadRequest<string>> =
  route.post(...).use(Parser.body(bodyCodec)).handler(...)
```

In this case `myRoute` would be used as the operation id.

A PR would be awesome!
